export const pragma = '/* auto-generated by @geekjuice/style */';

export const commands = {
  eslint: 'eslint',
  prettier: 'prettier',
};

export const flags = {
  eslint: [
    '--ext=.{js,mjs,ts,tsx}',
    '--report-unused-disable-directives',
    '--no-error-on-unmatched-pattern',
  ],
  prettier: [
    '--config-precedence=file-override',
    '--ignore-unknown',
    '--log-level=warn',
    '--no-error-on-unmatched-pattern',
    '--single-quote',
  ],
};
