export const PACKAGEJSON = 'package.json';
export const ESLINTRC = '.eslintrc.js';
export const PRETTIERRC = '.prettierrc.js';
export const HUSKYRC = '.huskyrc.js';
export const LINTSTAGEDRC = '.lintstagedrc.js';

export const BIN = './node_modules/.bin';
export const STYLES = './node_modules/@geekjuice/style';

export const PRAGMA = '/* autogenerated by @geekjuice/style */';

export const ESLINT_GLOB = '**/*.{js,jsx,ts,tsx}';
export const PRETTIER_GLOB =
  '**/*.{css,graphql,html,js,json,jsx,md,ts,tsx,yaml,yml}';
